accounts/urls.py
from django.conf.urls import url

from . import views


app_name = 'accounts'
urlpatterns = [
    url(r'^signout/$', views.auth_logout, name='logout'),
    url(r'^password/change/$', views.password_change, name="password_change"),
    url(r'^password/reset/$', views.password_reset, name="password_reset"),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.password_reset_confirm, name="password_reset_confirm"),
    url(r'^email/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.account_email_confirm, name="account_email_confirm"),
]

api/urls.py
from django.conf.urls import url


from . import views
from .views import APIHomeView
from .views import (AccountCreateAPIView,
                    MyUserDetailAPIView, MyUserListAPIView,
                    DriverDetailAPIView)
from .views import (PasswordChangeView, PasswordResetView,
                    PasswordResetConfirmView)
from .views import (ReservationCreateAPIView, ReservationDetailAPIView,
                    ReservationListAPIView)


# app_name = 'api'
urlpatterns = [
    # G E N E R A L
    url(r'^$', APIHomeView.as_view(),
        name='api_home'),

    # A C C O U N T S
    url(r'^accounts/$',
        MyUserListAPIView.as_view(),
        name='user_account_list_api'),
    url(r'^accounts/create/$',
        AccountCreateAPIView.as_view(),
        name='account_create_api'),
    url(r'^accounts/(?P<id>\d+)/$',
        MyUserDetailAPIView.as_view(),
        name='user_account_detail_api'),
    url(r'^accounts/driver/(?P<id>\d+)/$',
        DriverDetailAPIView.as_view(),
        name='user_driver_detail_api'),

    # A U T H E N T I C A T I O N
    url(r'^password/reset/$',
        PasswordResetView.as_view(),
        name='rest_password_reset'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(),
        name='rest_password_reset_confirm'),
    url(r'^password/change/$',
        PasswordChangeView.as_view(),
        name='rest_password_change'),

    # R E S E R V A T I O N S
    url(r'^reservations/$',
        ReservationListAPIView.as_view(),
        name='reservation_list_api'),
    url(r'^reservations/(?P<reservation_id>\d+)/$',
        ReservationDetailAPIView.as_view(),
        name='reservation_detail_api'),
    url(r'^reservations/create/$',
        ReservationCreateAPIView.as_view({'post': 'create'}),
        name='reservation_create_api'),
    url(r'^reservations/accept/(?P<reservation_id>\d+)/$',
        views.reservation_accept_api,
        name='reservation_accept_api'),
    url(r'^reservations/driver/found/(?P<reservation_id>\d+)/(?P<driver_id>\d+)/$',
        views.reservation_driver_found_api,
        name='reservation_driver_found_api'),
    url(r'^reservations/complete/(?P<reservation_id>\d+)/$',
        views.reservation_complete_api,
        name='reservation_complete_api'),
    url(r'^reservations/cancel/(?P<reservation_id>\d+)/$',
        views.reservation_cancel_api,
        name='reservation_cancel_api'),
]

accounts/models.py
from __future__ import unicode_literals

from datetime import datetime

from django.conf import settings
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _

# from phonenumber_field.modelfields import PhoneNumberField

from core.models import TimeStampedModel

# Create models here.


def upload_location(instance, filename):
    """
    Saves the uploaded file under the directory:
    'id/profile_pictures/filename'.
    """
    return "{}/profile_pictures/{}".format(instance.id, filename)


class MyUserManager(BaseUserManager):
    def create_user(self, email=None, password=None):
        """
        Creates a user in the database.
        """
        if not email:
            raise ValueError('Users must have an email address')

        now = datetime.now()
        user = self.model(
            email=self.normalize_email(email),
            date_joined=now, last_login=now
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates a superuser in the database.
        """
        user = self.create_user(
            email=email,
            password=password
        )
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(verbose_name='email',
                              max_length=80, unique=True)
    full_name = models.CharField(max_length=120, default='Temporary Name')
    profile_picture = models.ImageField(upload_to=upload_location, blank=True)
    # phone_number = PhoneNumberField(
    #     blank=True, help_text='When saving, format must be +1XXXXXXXXXX')
    phone_number = models.CharField(max_length=18, blank=True)
    university = models.CharField(max_length=180, blank=True)
    is_active = models.BooleanField(_('active'), default=True)
    is_admin = models.BooleanField(_('admin'), default=False)
    is_confirmed = models.BooleanField(_('confirmed'), default=False)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'

    class Meta:
        app_label = 'accounts'

    def __unicode__(self):
        return u"{}".format(self.full_name)

    def get_profile_view(self):
        """
        Returns the url to a user's profile.
        """
        return reverse('profile_view', kwargs={"id": self.id})

    @cached_property
    def get_short_name(self):
        """
        Returns the full name of a user.
        """
        return "{}".format(self.full_name)

    def has_module_perms(self, app_label):
        """
        Does the user have permissions to view the app `app_label`?
        """
        return True

    def has_perm(self, perm, obj=None):
        """
        Does the user have a specific permission?
        """
        return True

    @property
    def default_profile_picture(self):
        """
        Returns the profile picture of a user. If there is no profile picture,
        a default one will be rendered.
        """
        if self.profile_picture:
            return "{}{}".format(settings.MEDIA_URL, self.profile_picture)
        return settings.STATIC_URL + 'img/default-no-profile-pic.jpg'

    @property
    def is_staff(self):
        """
        Is the user a member of staff?
        """
        return self.is_admin


class Driver(TimeStampedModel):
    NEW = 0
    GOOD = 1
    FAIR = 2
    POOR = 3

    CAR_CONDITIONS = (
        (NEW, _('New')),
        (GOOD, _('Good')),
        (FAIR, _('Fair')),
        (POOR, _('Poor')),
    )
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='user')
    is_active = models.BooleanField(_('active'), default=True)
    car_make = models.CharField(max_length=30, blank=True)
    car_model = models.CharField(max_length=30, blank=True)
    car_status = models.IntegerField(
        choices=CAR_CONDITIONS, default=NEW)
    license_plate = models.CharField(max_length=12, blank=True)
    rating = models.IntegerField(default=0)
    trips_completed = models.IntegerField(default=0)

    class Meta:
        app_label = 'accounts'

    def __unicode__(self):
        return u"{}".format(self.user.full_name)

    def average_rating(self):
        """
        Returns the average rating of a driver.
        """
        if self.trips_completed > 0:
            return float("{0:.2f}".format(
                float(self.rating) / float(self.trips_completed)))
        return 0

    @cached_property
    def condition_verbose(self):
        """
        Returns the verbose of the reservation status.
        """
        return dict(Driver.CAR_CONDITIONS)[self.car_status]

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import (authenticate, login, logout,
                                 update_session_auth_hash)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import default_token_generator
from django.core.urlresolvers import reverse
from django.shortcuts import HttpResponseRedirect, redirect, render
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters

from .forms import (LoginForm, PasswordChangeForm,
                    RegisterForm, PasswordResetForm, SetPasswordForm)
from .models import MyUser

# Create your views here.


@sensitive_post_parameters()
@login_required
def password_change(request):
    """
    Renders a change password view for the current user.
    """
    form = PasswordChangeForm(request.POST or None, user=request.user)

    if request.method == "POST":
        if form.is_valid():
            password = form.cleaned_data['password2']
            current_user = form.user
            current_user.set_password(password)
            current_user.save()
            update_session_auth_hash(request, form.user)
            messages.success(request,
                             "You have successfully changed your password.")
    return render(request, 'accounts/settings/password_change.html',
                  {'form': form})


def password_reset(request, from_email=settings.FROM_EMAIL,
                   template_name='accounts/password_reset.html',
                   email_template_name='accounts/password_reset_email.html',
                   subject_template_name='Wipp Reset Password',
                   password_reset_form=PasswordResetForm,
                   token_generator=default_token_generator,
                   html_email_template_name='accounts/password_reset_email.html'):
    """
    Renders a reset change password view for the current user.
    """
    if request.user.is_authenticated():
        return redirect('home')
    else:
        if request.method == "POST":
            form = password_reset_form(request.POST)
            if form.is_valid():
                opts = {
                    'use_https': request.is_secure(),
                    'token_generator': token_generator,
                    'from_email': from_email,
                    'email_template_name': email_template_name,
                    'subject_template_name': subject_template_name,
                    'request': request,
                    'html_email_template_name': html_email_template_name,
                }
                form.save(**opts)
                messages.success(request,
                                 "If that email is registered to an account, "
                                 "instructions for resetting your password "
                                 "will be sent soon. Please make sure to check "
                                 "your junk email/spam folder if you do not "
                                 "receive an email.")
        else:
            form = password_reset_form()
        return render(request, template_name, {'form': form})


@sensitive_post_parameters()
@never_cache
def password_reset_confirm(request, uidb64=None, token=None,
                           token_generator=default_token_generator):
    assert uidb64 is not None and token is not None
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = MyUser._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, MyUser.DoesNotExist):
        user = None

    if user is not None and token_generator.check_token(user, token):
        validlink = True
        form = SetPasswordForm(request.POST or None, user=user)
        if request.method == 'POST':
            if form.is_valid():
                form.save()
                messages.success(request, "Password reset successfully")
                return HttpResponseRedirect(reverse("home"))
    else:
        validlink = False
        form = None
        messages.error(request, "Password reset unsuccessful")
    context = {
        'form': form,
        'validlink': validlink
    }
    return render(request, 'accounts/password_set.html', context)


def auth_logout(request):
    """
    Logs out the current user.
    """
    logout(request)
    return HttpResponseRedirect(reverse("home"))


def auth_login(request):
    """
    Logs in the user.
    """
    if request.user.is_authenticated():
        return redirect("home")
    else:
        form = LoginForm(request.POST or None)
        next_url = request.GET.get('next')

        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(email=email, password=password)

            if user is not None:
                login(request, user)

                if next_url is not None:
                    return HttpResponseRedirect(next_url)
                return HttpResponseRedirect(reverse("home"))
            else:
                messages.warning(request, "Username or password is incorrect.")
        action_url = reverse("login")
        title = "Sign in"
        submit_btn = title
        context = {
            "form": form,
            "action_url": action_url,
            "title": title,
            "submit_btn": submit_btn
        }
        return render(request, 'login_register.html', context)


def auth_register(request):
    """
    Renders a view for users to register on the website.
    """
    if request.user.is_authenticated():
        return redirect("home")
    else:
        form = RegisterForm(request.POST or None)
        next_url = request.GET.get('next')

        if form.is_valid():
            full_name = form.cleaned_data['full_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password2']
            phone_number = form.cleaned_data['phone_number']
            new_user = MyUser()
            new_user.full_name = full_name
            new_user.email = email
            new_user.set_password(password)
            new_user.phone_number = phone_number
            new_user.save()
            user = authenticate(email=email, password=password)
            if user is not None:
                login(request, user)

                if next_url is not None:
                    return HttpResponseRedirect(next_url)
                return HttpResponseRedirect(reverse("home"))
        action_url = reverse("register")
        title = "Register"
        submit_btn = "Create account"
        context = {
            "form": form,
            "action_url": action_url,
            "title": title,
            "submit_btn": submit_btn
        }
        return render(request, "login_register.html", context)


@sensitive_post_parameters()
@never_cache
def account_email_confirm(request, uidb64=None, token=None,
                          token_generator=default_token_generator):
    assert uidb64 is not None and token is not None
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = MyUser._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, MyUser.DoesNotExist):
        user = None

    if user is not None and token_generator.check_token(user, token):
        validlink = True
        user.is_confirmed = True
        user.save()
        messages.success(request, "Thank you for confirming your email!")
        return HttpResponseRedirect(reverse("home"))
    else:
        validlink = False
        messages.error(request, "Email confirmation unsuccessful")
    context = {
        'validlink': validlink
    }
    return render(request, 'home.html', context)

templates/accounts/email_confirm_message.html
<!doctype html>
<html>
<head>
<meta name="viewport" content="width=device-width">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Wipp Email Confirmation</title>
<style>
/* -------------------------------------
    GLOBAL
------------------------------------- */
* {
  font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
  font-size: 100%;
  line-height: 1.6em;
  margin: 0;
  padding: 0;
}
img {
  max-width: 600px;
  width: 100%;
}
body {
  -webkit-font-smoothing: antialiased;
  height: 100%;
  -webkit-text-size-adjust: none;
  width: 100% !important;
}
/* -------------------------------------
    ELEMENTS
------------------------------------- */
a {
  color: #348eda;
}
.btn-primary {
  Margin-bottom: 10px;
  width: auto !important;
}
.btn-primary td {
  background-color: #348eda; 
  border-radius: 25px;
  font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif; 
  font-size: 14px; 
  text-align: center;
  vertical-align: top; 
}
.btn-primary td a {
  background-color: #348eda;
  border: solid 1px #348eda;
  border-radius: 25px;
  border-width: 10px 20px;
  display: inline-block;
  color: #ffffff;
  cursor: pointer;
  font-weight: bold;
  line-height: 2;
  text-decoration: none;
}
.last {
  margin-bottom: 0;
}
.first {
  margin-top: 0;
}
.padding {
  padding: 10px 0;
}
/* -------------------------------------
    BODY
------------------------------------- */
table.body-wrap {
  padding: 20px;
  width: 100%;
}
table.body-wrap .container {
  border: 1px solid #f0f0f0;
}
/* -------------------------------------
    FOOTER
------------------------------------- */
table.footer-wrap {
  clear: both !important;
  width: 100%;  
}
.footer-wrap .container p {
  color: #666666;
  font-size: 12px;
  
}
table.footer-wrap a {
  color: #999999;
}
/* -------------------------------------
    TYPOGRAPHY
------------------------------------- */
h1, 
h2, 
h3 {
  color: #111111;
  font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
  font-weight: 200;
  line-height: 1.2em;
  margin: 40px 0 10px;
}
h1 {
  font-size: 36px;
}
h2 {
  font-size: 28px;
}
h3 {
  font-size: 22px;
}
p, 
ul, 
ol {
  font-size: 14px;
  font-weight: normal;
  margin-bottom: 10px;
}
ul li, 
ol li {
  margin-left: 5px;
  list-style-position: inside;
}
/* ---------------------------------------------------
    RESPONSIVENESS
------------------------------------------------------ */
.container {
  clear: both !important;
  display: block !important;
  Margin: 0 auto !important;
  max-width: 600px !important;
}
.body-wrap .container {
  padding: 20px;
}
.content {
  display: block;
  margin: 0 auto;
  max-width: 600px;
}
.content table {
  width: 100%;
}
</style>
</head>

<body bgcolor="#f6f6f6">

<!-- body -->
<table class="body-wrap" bgcolor="#f6f6f6">
  <tr>
    <td></td>
    <td class="container" bgcolor="#FFFFFF">

      <!-- content -->
      <div class="content">
      <table>
        <tr>
          <td>
            <p>Hi,</p>
            <p>Thank you for registering on Wipp! Before you continue using your account, please confirm your email by clicking the button below:</p>
            <h2>Confirm email:</h2>
            <!-- button -->
            <table class="btn-primary" cellpadding="0" cellspacing="0" border="0">
              <tr>
                <td>
                  <a href="{{ protocol }}://{{ domain }}{% url 'accounts:account_email_confirm' uidb64=uid token=token %}">CONFIRM EMAIL</a>
                </td>
              </tr>
            </table>
            <!-- /button -->
            <br/>
            <br/>
            <!-- Line below doesn't work -->
            <p>If you forgot, your registered email is: <b>{{ email }}</b></p>  
            <p>If you don't think this was you, please ignore this email.</p>
            <p>Thanks for using Wipp!</p>
            <p><a href="{{ protocol }}://{{ domain }}"></a>{{ protocol }}://{{ domain }}</p>
          </td>
        </tr>
      </table>
      </div>
      <!-- /content -->
    </td>
    <td></td>
  </tr>
</table>
<!-- /body -->

<!-- footer -->
<table class="footer-wrap">
  <tr>
    <td></td>
    <td class="container">
      
      <!-- content -->
      <div class="content">
        <table>
          <tr>
            <td align="center">
              <!-- <p>Don't like these emails? <a href="#"><unsubscribe>Unsubscribe</unsubscribe></a>.</p> -->
            </td>
          </tr>
        </table>
      </div>
      <!-- /content -->
      
    </td>
    <td></td>
  </tr>
</table>
<!-- /footer -->

</body>
</html>

templates/accounts/password_reset_email.html
<!doctype html>
<html>
<head>
<meta name="viewport" content="width=device-width">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Wipp Reset Password</title>
<style>
/* -------------------------------------
    GLOBAL
------------------------------------- */
* {
  font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
  font-size: 100%;
  line-height: 1.6em;
  margin: 0;
  padding: 0;
}
img {
  max-width: 600px;
  width: 100%;
}
body {
  -webkit-font-smoothing: antialiased;
  height: 100%;
  -webkit-text-size-adjust: none;
  width: 100% !important;
}
/* -------------------------------------
    ELEMENTS
------------------------------------- */
a {
  color: #348eda;
}
.btn-primary {
  Margin-bottom: 10px;
  width: auto !important;
}
.btn-primary td {
  background-color: #348eda; 
  border-radius: 25px;
  font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif; 
  font-size: 14px; 
  text-align: center;
  vertical-align: top; 
}
.btn-primary td a {
  background-color: #348eda;
  border: solid 1px #348eda;
  border-radius: 25px;
  border-width: 10px 20px;
  display: inline-block;
  color: #ffffff;
  cursor: pointer;
  font-weight: bold;
  line-height: 2;
  text-decoration: none;
}
.last {
  margin-bottom: 0;
}
.first {
  margin-top: 0;
}
.padding {
  padding: 10px 0;
}
/* -------------------------------------
    BODY
------------------------------------- */
table.body-wrap {
  padding: 20px;
  width: 100%;
}
table.body-wrap .container {
  border: 1px solid #f0f0f0;
}
/* -------------------------------------
    FOOTER
------------------------------------- */
table.footer-wrap {
  clear: both !important;
  width: 100%;  
}
.footer-wrap .container p {
  color: #666666;
  font-size: 12px;
  
}
table.footer-wrap a {
  color: #999999;
}
/* -------------------------------------
    TYPOGRAPHY
------------------------------------- */
h1, 
h2, 
h3 {
  color: #111111;
  font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
  font-weight: 200;
  line-height: 1.2em;
  margin: 40px 0 10px;
}
h1 {
  font-size: 36px;
}
h2 {
  font-size: 28px;
}
h3 {
  font-size: 22px;
}
p, 
ul, 
ol {
  font-size: 14px;
  font-weight: normal;
  margin-bottom: 10px;
}
ul li, 
ol li {
  margin-left: 5px;
  list-style-position: inside;
}
/* ---------------------------------------------------
    RESPONSIVENESS
------------------------------------------------------ */
.container {
  clear: both !important;
  display: block !important;
  Margin: 0 auto !important;
  max-width: 600px !important;
}
.body-wrap .container {
  padding: 20px;
}
.content {
  display: block;
  margin: 0 auto;
  max-width: 600px;
}
.content table {
  width: 100%;
}
</style>
</head>

<body bgcolor="#f6f6f6">

<!-- body -->
<table class="body-wrap" bgcolor="#f6f6f6">
  <tr>
    <td></td>
    <td class="container" bgcolor="#FFFFFF">

      <!-- content -->
      <div class="content">
      <table>
        <tr>
          <td>
            <p>Hi,</p>
            <p>Your email was entered in the forgotten password form at Wipp.<br/>
            If you made this request, please click the button below to create a new password:</p>
            <h2>Password reset:</h2>
            <!-- button -->
            <table class="btn-primary" cellpadding="0" cellspacing="0" border="0">
              <tr>
                <td>
                  <a href="{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}">RESET PASSWORD</a>
                </td>
              </tr>
            </table>
            <!-- /button -->
            <br/>
            <br/>
            <p>If you forgot, your email is: <b>{{ email }}</b></p>
            <p>If you don't think this was you, please ignore this email.</p>
            <p>Thanks for using Wipp!</p>
            <p><a href="http://127.0.0.1:8000/">127.0.0.1:8000</a></p>
          </td>
        </tr>
      </table>
      </div>
      <!-- /content -->
    </td>
    <td></td>
  </tr>
</table>
<!-- /body -->

<!-- footer -->
<table class="footer-wrap">
  <tr>
    <td></td>
    <td class="container">
      
      <!-- content -->
      <div class="content">
        <table>
          <tr>
            <td align="center">
              <!-- <p>Don't like these annoying emails? <a href="#"><unsubscribe>Unsubscribe</unsubscribe></a>.</p> -->
            </td>
          </tr>
        </table>
      </div>
      <!-- /content -->
      
    </td>
    <td></td>
  </tr>
</table>
<!-- /footer -->

</body>
</html>

templates/accounts/password_set.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}Wipp - Set Password{% endblock title %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3 password-container">
        <h1>Create New Password</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="submit-btn reset-btn" type="submit" value="Create Password" />
        </form>    
    </div>
{% endblock content %}